In [4]:
from src.dataset.load import *
from src.features.process_race_header import *
from src.features.process_race_infos import *

In [5]:
race_info_path = Path("../data/raw/race_info")
race_header_path = Path("../data/raw/race_header")
#race_info_files = [f.name for f in race_info_path.iterdir() if f.is_file()]

In [6]:
example_id = 172134

In [7]:
race_infos = load_race_infos(race_info_path, example_id)
race_header = load_race_infos(race_header_path, example_id)

In [8]:
race_header

,raceTime,raceDate,raceId,raceTitle,raceNumber,raceType,raceHandicap,raceClass,raceDistance,racePrizes,raceGoing,raceForecast,raceTricast,meeting_Id
0,18:18:00,07/12/2015,172134,NaN,14,Flat,False,A4,500.0,1st £100 | Others £30 | Race Total £250,20,(4-3) £23.28,(4-3-5) £76.07,307402

In [9]:
race_infos

,trapNumber,trapHandicap,dogId,dogName,dogSire,dogDam,dogBorn,dogColour,dogSex,dogSeason,...,resultMarketPos,resultMarketCnt,resultPriceNumerator,resultPriceDenominator,resultBtnDistance,resultSectionalTime,resultComment,resultRunTime,resultDogWeight,resultAdjustedTime
0,4,NaN,429350,Geelo Lilo,Westmead Hawk,Coolbeggan Lass,Jan-2012,bk,d,NaN,...,6,1,6,1,NaN,4.29,Crowded&Led1,29.37,32.8,29.57
1,3,NaN,453534,Bodell Pearl,Kinloch Brae,Varra Kate,Aug-2013,bk,b,20.Ap.15,...,1,1,6,4,3 1/2,4.34,Crowded1,29.65,27.6,29.85
2,5,NaN,440128,Rock Critic,Cashen Legend,Fair Fantasy,Aug-2012,bk,d,NaN,...,4,1,5,1,3/4,4.37,Crowded1,29.71,36.3,29.91
3,6,NaN,449557,Bravo Sonshine,Razldazl Jayfkay,Lifes Mega,Mar-2013,bd,d,NaN,...,3,1,4,1,NK,4.34,EveryChance,29.74,35.4,29.94
4,2,NaN,448006,Slaneyside Trixy,Smooth Daddy,Garabaldi,May-2013,f,b,Unknown,...,5,1,11,2,1,4.41,ForcedToCk2,29.82,23.7,30.02
5,1,NaN,462338,Marinas Spark,Shaneboy Lee,Marinas Blue,Sep-2013,wbk,d,NaN,...,2,1,3,1,5 3/4,4.45,"SAw,EveryChance",30.28,35.5,30.48

In [10]:
race_header_processed = preprocess_pipeline_race_header(race_header)

In [14]:
race_info_processed, race_result_positions, race_date = preprocess_pipeline_race_info(race_header, race_infos)

In [16]:
race_info_processed

,dogId,trapNumber_1,trapNumber_2,trapNumber_3,trapNumber_4,trapNumber_5,trapNumber_6,dogSex_b,dogSex_d,trapNumber,dogAge
0,462338,1,0,0,0,0,0,0,1,1,2.264203
1,448006,0,1,0,0,0,0,1,0,2,2.600958
2,453534,0,0,1,0,0,0,1,0,3,2.349076
3,429350,0,0,0,1,0,0,0,1,4,3.931554
4,440128,0,0,0,0,1,0,0,1,5,3.348392
5,449557,0,0,0,0,0,1,0,1,6,2.767967

In [17]:
race_result_positions

0    6
1    5
2    2
3    1
4    3
5    4
Name: resultPosition, dtype: int64

In [18]:
race_date

Timestamp('2015-12-07 00:00:00')